# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# Exclude heavy packages that aren't essential for the core functionality
excludes = [
    'matplotlib',
    'scipy',
    'pandas',
    'torch',
    'tensorflow',
    'keras',
    'sklearn',
    'cv2',
    'PIL',
    'IPython',
    'jupyter',
    'notebook',
    'sympy',
    'h5py',
    'pyarrow',
    'kivy',
    'kivymd',
    'pygame',
    'PyQt5',
    'PyQt6',
    'PySide2',
    'PySide6',
    'wx',
    'flet',
    'plotly',
    'bokeh',
    'seaborn',
    'statsmodels',
    'networkx',
    'nltk',
    'spacy',
    'transformers',
    'datasets',
    'accelerate',
    'diffusers',
    'tokenizers',
    'huggingface_hub',
    'wandb',
    'tensorboard',
    'mlflow',
    'optuna',
    'ray',
    'dask',
    'numba',
    'cupy',
    'jax',
    'flax',
    'gym',
    'stable_baselines3',
    'opencv-python',
    'opencv-contrib-python',
    'mediapipe',
    'ultralytics',
    'detectron2',
    'mmcv',
    'mmdet',
    'mmseg',
    'mmpose',
    'mmaction2',
    'mmtracking',
    'mmocr',
    'mmgen',
    'mmselfsup',
    'mmrazor',
    'mmfewshot',
    'mmhuman3d',
    'mmrotate',
    'mmflow',
    'mmedit',
    'mmcls',
    'test',
    'tests',
    'testing',
    'unittest',
    'doctest',
    'pdb',
    'pydoc',
    'xmlrpc',
    'wsgiref',
    'distutils',
    'lib2to3',
    'tkinter.test',
    'idlelib',
    'turtledemo'
]

a = Analysis(
    ['realtime_voice_translator.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('translator_config.json', '.'),
        ('icon.ico', '.'),
        ('icon.png', '.'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.scrolledtext',
        'tkinter.messagebox',
        'pyaudio',
        'openai',
        'numpy',
        'google.generativeai',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# Remove duplicate entries and unnecessary files
a.datas = [x for x in a.datas if not any(exclude in x[0].lower() for exclude in [
    'test', 'example', 'demo', 'doc', 'readme', 'license', 'changelog',
    'matplotlib', 'scipy', 'pandas', 'torch', 'tensorflow', 'keras',
    'sklearn', 'cv2', 'pil', 'ipython', 'jupyter', 'kivy', 'pygame'
])]

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='RealTimeVoiceTranslator_Optimized',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,  # Strip debug symbols
    upx=True,    # Use UPX compression
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',  # Use the icon file
)